from __future__ import annotations

from collections.abc import Hashable
from typing import Any

from ._edgestream import StreamGraph as StreamGraph

__version__: str

class NodeIndex:
    def __init__(self) -> None: ...
    def __getitem__(self, key: Hashable) -> int: ...
    def id(self, key: Hashable) -> int: ...
    def key(self, node_id: int) -> Any: ...
    def n_nodes(self) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def keys(self) -> list[Any]: ...
    def ids(self) -> list[int]: ...

def to_networkx(G: StreamGraph, index: NodeIndex | None = None) -> Any: ...
def from_networkx(nxg: Any) -> tuple[StreamGraph, NodeIndex]: ...
def to_scipy_sparse(G: StreamGraph) -> Any: ...

class SlidingWindowGraph:
    graph: StreamGraph
    window: float
    def __init__(
        self,
        window: float,
        *,
        n_nodes: int = 0,
        directed: bool = False,
        weighted: bool = False,
    ) -> None: ...
    def advance(self, timestamp: float) -> int: ...
    def add_edge(self, u: int, v: int, timestamp: float, w: float = 1.0) -> bool: ...
    def snapshot(self) -> StreamGraph: ...
