# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.sg_create <- function(n_nodes, directed, weighted) {
    .Call(`_edgestream_sg_create`, n_nodes, directed, weighted)
}

.sg_add_node <- function(ptr, u) {
    .Call(`_edgestream_sg_add_node`, ptr, u)
}

.sg_add_nodes <- function(ptr, start, count) {
    .Call(`_edgestream_sg_add_nodes`, ptr, start, count)
}

.sg_nodes <- function(ptr) {
    .Call(`_edgestream_sg_nodes`, ptr)
}

.sg_reserve_nodes <- function(ptr, n) {
    invisible(.Call(`_edgestream_sg_reserve_nodes`, ptr, n))
}

.sg_reserve_edges <- function(ptr, m) {
    invisible(.Call(`_edgestream_sg_reserve_edges`, ptr, m))
}

.sg_clear <- function(ptr) {
    invisible(.Call(`_edgestream_sg_clear`, ptr))
}

.sg_add_edge <- function(ptr, u, v, w) {
    .Call(`_edgestream_sg_add_edge`, ptr, u, v, w)
}

.sg_remove_edge <- function(ptr, u, v) {
    .Call(`_edgestream_sg_remove_edge`, ptr, u, v)
}

.sg_update_edge_weight <- function(ptr, u, v, w) {
    .Call(`_edgestream_sg_update_edge_weight`, ptr, u, v, w)
}

.sg_same_component <- function(ptr, u, v) {
    .Call(`_edgestream_sg_same_component`, ptr, u, v)
}

.sg_component_id <- function(ptr, u) {
    .Call(`_edgestream_sg_component_id`, ptr, u)
}

.sg_n_components <- function(ptr) {
    .Call(`_edgestream_sg_n_components`, ptr)
}

.sg_component_size <- function(ptr, u) {
    .Call(`_edgestream_sg_component_size`, ptr, u)
}

.sg_degree <- function(ptr, u) {
    .Call(`_edgestream_sg_degree`, ptr, u)
}

.sg_in_degree <- function(ptr, u) {
    .Call(`_edgestream_sg_in_degree`, ptr, u)
}

.sg_strength <- function(ptr, u) {
    .Call(`_edgestream_sg_strength`, ptr, u)
}

.sg_has_edge <- function(ptr, u, v) {
    .Call(`_edgestream_sg_has_edge`, ptr, u, v)
}

.sg_edge_weight <- function(ptr, u, v) {
    .Call(`_edgestream_sg_edge_weight`, ptr, u, v)
}

.sg_total_weight <- function(ptr) {
    .Call(`_edgestream_sg_total_weight`, ptr)
}

.sg_neighbours <- function(ptr, u) {
    .Call(`_edgestream_sg_neighbours`, ptr, u)
}

.sg_in_neighbours <- function(ptr, u) {
    .Call(`_edgestream_sg_in_neighbours`, ptr, u)
}

.sg_n_nodes <- function(ptr) {
    .Call(`_edgestream_sg_n_nodes`, ptr)
}

.sg_n_ids <- function(ptr) {
    .Call(`_edgestream_sg_n_ids`, ptr)
}

.sg_n_edges <- function(ptr) {
    .Call(`_edgestream_sg_n_edges`, ptr)
}

.sg_is_directed <- function(ptr) {
    .Call(`_edgestream_sg_is_directed`, ptr)
}

.sg_is_weighted <- function(ptr) {
    .Call(`_edgestream_sg_is_weighted`, ptr)
}

.sg_triangle_count <- function(ptr) {
    .Call(`_edgestream_sg_triangle_count`, ptr)
}

.sg_local_triangles <- function(ptr, u) {
    .Call(`_edgestream_sg_local_triangles`, ptr, u)
}

.sg_all_local_triangles <- function(ptr) {
    .Call(`_edgestream_sg_all_local_triangles`, ptr)
}

.sg_clustering_coefficient <- function(ptr, u) {
    .Call(`_edgestream_sg_clustering_coefficient`, ptr, u)
}

.sg_avg_clustering <- function(ptr) {
    .Call(`_edgestream_sg_avg_clustering`, ptr)
}

.sg_add_edges <- function(ptr, us, vs, ws, n_threads) {
    .Call(`_edgestream_sg_add_edges`, ptr, us, vs, ws, n_threads)
}

.sg_density <- function(ptr) {
    .Call(`_edgestream_sg_density`, ptr)
}

.sg_avg_degree <- function(ptr) {
    .Call(`_edgestream_sg_avg_degree`, ptr)
}

.sg_max_degree <- function(ptr) {
    .Call(`_edgestream_sg_max_degree`, ptr)
}

.sg_degree_histogram <- function(ptr) {
    .Call(`_edgestream_sg_degree_histogram`, ptr)
}

.sg_component_nodes <- function(ptr, u) {
    .Call(`_edgestream_sg_component_nodes`, ptr, u)
}

.sg_component_ids <- function(ptr) {
    .Call(`_edgestream_sg_component_ids`, ptr)
}

.sg_strong_component_ids <- function(ptr) {
    .Call(`_edgestream_sg_strong_component_ids`, ptr)
}

.sg_n_strong_components <- function(ptr) {
    .Call(`_edgestream_sg_n_strong_components`, ptr)
}

.sg_edge_list <- function(ptr) {
    .Call(`_edgestream_sg_edge_list`, ptr)
}

.sg_pagerank <- function(ptr, damping, tol, max_iter) {
    .Call(`_edgestream_sg_pagerank`, ptr, damping, tol, max_iter)
}

.sg_betweenness_approx <- function(ptr, k, n_threads, seed, normalise) {
    .Call(`_edgestream_sg_betweenness_approx`, ptr, k, n_threads, seed, normalise)
}

.sg_save <- function(ptr, path) {
    invisible(.Call(`_edgestream_sg_save`, ptr, path))
}

.sg_load <- function(path) {
    .Call(`_edgestream_sg_load`, path)
}

.sg_copy <- function(source) {
    .Call(`_edgestream_sg_copy`, source)
}

