# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.sg_create <- function(n_nodes, directed) {
    .Call(`_streamgraph_sg_create`, n_nodes, directed)
}

.sg_add_edge <- function(ptr, u, v) {
    .Call(`_streamgraph_sg_add_edge`, ptr, u, v)
}

.sg_same_component <- function(ptr, u, v) {
    .Call(`_streamgraph_sg_same_component`, ptr, u, v)
}

.sg_component_id <- function(ptr, u) {
    .Call(`_streamgraph_sg_component_id`, ptr, u)
}

.sg_n_components <- function(ptr) {
    .Call(`_streamgraph_sg_n_components`, ptr)
}

.sg_component_size <- function(ptr, u) {
    .Call(`_streamgraph_sg_component_size`, ptr, u)
}

.sg_degree <- function(ptr, u) {
    .Call(`_streamgraph_sg_degree`, ptr, u)
}

.sg_in_degree <- function(ptr, u) {
    .Call(`_streamgraph_sg_in_degree`, ptr, u)
}

.sg_has_edge <- function(ptr, u, v) {
    .Call(`_streamgraph_sg_has_edge`, ptr, u, v)
}

.sg_neighbours <- function(ptr, u) {
    .Call(`_streamgraph_sg_neighbours`, ptr, u)
}

.sg_in_neighbours <- function(ptr, u) {
    .Call(`_streamgraph_sg_in_neighbours`, ptr, u)
}

.sg_n_nodes <- function(ptr) {
    .Call(`_streamgraph_sg_n_nodes`, ptr)
}

.sg_n_edges <- function(ptr) {
    .Call(`_streamgraph_sg_n_edges`, ptr)
}

.sg_triangle_count <- function(ptr) {
    .Call(`_streamgraph_sg_triangle_count`, ptr)
}

.sg_local_triangles <- function(ptr, u) {
    .Call(`_streamgraph_sg_local_triangles`, ptr, u)
}

.sg_all_local_triangles <- function(ptr) {
    .Call(`_streamgraph_sg_all_local_triangles`, ptr)
}

.sg_add_edges <- function(ptr, us, vs, n_threads) {
    .Call(`_streamgraph_sg_add_edges`, ptr, us, vs, n_threads)
}

.sg_density <- function(ptr) {
    .Call(`_streamgraph_sg_density`, ptr)
}

.sg_avg_degree <- function(ptr) {
    .Call(`_streamgraph_sg_avg_degree`, ptr)
}

.sg_max_degree <- function(ptr) {
    .Call(`_streamgraph_sg_max_degree`, ptr)
}

.sg_degree_histogram <- function(ptr) {
    .Call(`_streamgraph_sg_degree_histogram`, ptr)
}

.sg_component_nodes <- function(ptr, u) {
    .Call(`_streamgraph_sg_component_nodes`, ptr, u)
}

.sg_component_ids <- function(ptr) {
    .Call(`_streamgraph_sg_component_ids`, ptr)
}

.sg_betweenness_approx <- function(ptr, k, n_threads, seed, normalise) {
    .Call(`_streamgraph_sg_betweenness_approx`, ptr, k, n_threads, seed, normalise)
}

.sg_save <- function(ptr, path) {
    invisible(.Call(`_streamgraph_sg_save`, ptr, path))
}

.sg_load <- function(path) {
    .Call(`_streamgraph_sg_load`, path)
}

